In [1]:
! pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr*2

array([ 2,  4,  6,  8, 10])

In [5]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
#We use numpy arrays when we want to perform operations on the elements of a list or array

In [9]:
my_list = [5,6,7,8,9]
a = np.array(my_list)
print(a)

[5 6 7 8 9]
